_security_login:
    path:  /login
    defaults: { _controller: 'AppBundle:Security:login' }

_security_check:
    path:  /login_check

_security_logout:
    path:  /logout

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
