# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.cats:
        class: AppBundle\Utils\CategoriesService

    app.menu_builder:
            class: AppBundle\Utils\MenuBuilderService
            arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager"]
            tags:
                - { name: knp_menu.menu_builder, method: buildCategoriesMenu, alias: categories }

