# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.cats:
        class: AppBundle\Utils\CategoriesService

    app.menu_builder:
            class: AppBundle\Utils\MenuBuilderService
            arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager"]
            tags:
                - { name: knp_menu.menu_builder, method: buildCategoriesMenu, alias: categories }

    admin.category:
            class: AppBundle\Entity\DBCategoryAdmin
            arguments: [~, AppBundle\Entity\DBCategory, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Категории }

    admin.item:
            class: AppBundle\Entity\DBItemAdmin
            arguments: [~, AppBundle\Entity\DBItem, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Товары }

    admin.order:
            class: AppBundle\Entity\DBOrderAdmin
            arguments: [~, AppBundle\Entity\DBOrder, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Заказы }

    admin.order_item:
            class: AppBundle\Entity\DBOrderItemAdmin
            arguments: [~, AppBundle\Entity\DBOrderItem, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: 'Элемент списка заказа', show_in_dashboard: false }

    admin.user:
            class: AppBundle\Entity\DBUserAdmin
            arguments: [~, AppBundle\Entity\DBUser, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Пользователи }

    admin.role:
            class: AppBundle\Entity\DBRoleAdmin
            arguments: [~, AppBundle\Entity\DBRole, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Роли }