<?php

namespace AppBundle\Entity;

/**
 * DBOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DBOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
